Allow non existing PSets for MTE #69
mgehre/llvm-project pull request #78
Opened 2019-11-05 18:39 UTC by lklein53

Materialize Temporary Expr don't always have a pset in the RefersTo or
PSetsOfExpr Maps.
In the example that showed the issue the MaterializeTemporaryExpr
was bound to an integer literal.

2019-11-06 19:08 UTC, lklein53 commented
> I'm not sure if ignoring is the right approach. Can you explain why some MaterializeTemporaryExpr
> have psets and some have not?
> 
> On the example code, I get
> 
> ```
>  warning: returning reference to local temporary object [-Wreturn-stack-address]
> const int &a::b() const { return 0; }
> ```
> 
> so we might want to have psets to diagnose those problematic references?
> E.g. in
> 
> ```
> const int& m = std::min(1,2);
> ```
> 
> will `m` dangle because `1` is a MaterializeTemporaryExpr that is destroyed at end of line?
> 
> Could the PR get a test to show the psets of `m`?

With and without my change 
```
auto &m = min(1,2);
__lifetime_pset(m);
```
returns no pset. As the check for hasPset returns false.

Yes m is reported to dangle

2019-11-08 06:42 UTC, mgehre commented
> ```
> auto &m = min(1,2);
> __lifetime_pset(m);
> ```
> 
> returns no pset. As the check for hasPset returns false.
`__lifetime_pset(m)` looks at the pset of the integer that the reference points to and integers don't have psets. If you want to look at the pset of the reference you can use `__lifetime_pset_ref(m)`.

We have both `__lifetime_pset` and `__lifetime_pset_ref` because we could have a variable `int*& rp`.
If want to see the pset of the toplevel reference, use `__lifetime_pset_ref(rp)`. If you want to see the pset of the `int*` that `rp` points to, use `__lifetime_pset(rp)`.

2019-11-09 08:54 UTC, mgehre commented
What is our `__lifetime_pset_ref(a)`  for
```
const int& a = 0;
```
?

2019-11-09 17:53 UTC, lklein53 commented
> `const int& a = 0;`

lifetime-extended temporary

2019-11-10 18:46 UTC, mgehre requested changes

2019-11-10 18:46 UTC, mgehre commented on clang/lib/Analysis/LifetimePsetBuilder.cpp
> +      if (isa<Stmt>(S) && !isa<Expr>(S)) {
I think the static type of `S` is already `Stmt` ?

2019-11-10 18:46 UTC, mgehre commented on clang/lib/Analysis/LifetimePsetBuilder.cpp
> +        PSetsOfExpr.clear();
Can you update the comment above?

2019-11-10 21:08 UTC, mgehre approved these changes

2019-11-11 20:43 UTC, merged